version: '3.4'

services:
  we-client:
    image: wintang1103/we-client:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
    ports:
      - 3000:3000
