version: '3.4'

services:
  we-client:
    image: wintang1103/we-client:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ['node', '--inspect=0.0.0.0:9229', 'index.js']
